Footer links saving translation
Ukraine-Relief-Efforts/ukraine-info-guide pull request #211
Opened 2022-03-07 13:07 UTC by MnsrIl

When we move on the [border-info or resources] page by footer link, we lost selected translation language. 
Fixed it

P.S. Don't know, why this pull request contains the merge commits and "LocationCard styling". So, if anyone could help - please, welcome

2022-03-07 17:09 UTC, oetherington requested changes

2022-03-07 19:08 UTC, MnsrIl commented on hooks/useCountryData.js
> +    const handler = () => setSelectedCountry(nextCountryHash);
Yeah, it looks like

2022-03-07 21:31 UTC, MnsrIl commented on hooks/useCountryData.js
> +    const handler = () => setSelectedCountry(nextCountryHash);
So, should I restore it in both places? Or only here?

2022-03-09 11:46 UTC, MnsrIl commented
@oetherington could you please review this one and merge this PR?

2022-03-10 08:25 UTC, oetherington approved these changes

2022-03-10 08:25 UTC, merged